[project]
name = "vad-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "grpcio>=1.68.1",
    "grpcio-tools>=1.68.1",
    "numpy>=2.2.0",
    "opencv-python",
    "scipy>=1.14.1",
]
